### ISSUE TITLE
Operands could not be broadcast together

### ISSUE THREAD

**Issue by Arwa314** [imoken1122/GIST-feature-extractor#1]
I get this error after running main.py, this is what I get
```
$ python main.py --input_path sample --output_path gist.feather
 10%|█         | 3/30 [00:02<00:36,  1.35s/it]Namespace(input_path='sample', output_path='gist.feather', save=True)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\lenovo-pc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\lenovo-pc\Desktop\Training\GIST-feature-extractor\GIST.py", line 126, in _gist_extract
    output = self._prefilt(img)
  File "C:\Users\lenovo-pc\Desktop\Training\GIST-feature-extractor\GIST.py", line 81, in _prefilt
    output = img - np.real(f.ifft2(f.fft2(img)*gf))
ValueError: operands could not be broadcast together with shapes (4200,266) (4200,4200)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 66, in <module>
    gist_feature = _get_gist(param,file_list)
  File "main.py", line 52, in _get_gist
    gist_feature = list(tqdm(p, total = len(img_list)))
  File "C:\Users\lenovo-pc\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\std.py", line 1119, in __iter__
    for obj in iterable:
  File "C:\Users\lenovo-pc\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 865, in next
    raise value
ValueError: operands could not be broadcast together with shapes (4200,266) (4200,4200)
 10%|█         | 3/30 [00:09<01:27,  3.24s/it]
```

**Comment by jagadeeshEunimart** [comment]
Hey I'm facing the same error. What have you changed to make it work?
