### ISSUE TITLE
FileNotFoundError:  for a directory of image folders

### ISSUE THREAD

**Issue by sanchezanthony244** [imoken1122/GIST-feature-extractor#2]
I'm getting a FileNotFoundError: when this terminal command runs for a folder of .jpg images

$ python3 main.py --input_path home/anthony/Downloads/AUairdrone_data/images/validate --output_path home/anthony/Downloads/AUairdrone_data/image

the full error is:

Namespace(input_path='home/anthony/Downloads/AUairdrone_data/images/validate', output_path='home/anthony/Downloads/AUairdrone_data/image', save=True)
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    file_list = data.get_inputfile()
  File "main.py", line 30, in get_inputfile
    a = sorted(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: './home/anthony/Downloads/AUairdrone_data/images/validate/'

I'm not sure if it's just syntax or something that is not compatible, anyone know how to resolve this?

**Comment by sanchezanthony244** [comment]
> I'm getting a FileNotFoundError: when this terminal command runs for a folder of .jpg images
> 
> $ python3 main.py --input_path home/anthony/Downloads/AUairdrone_data/images/validate --output_path home/anthony/Downloads/AUairdrone_data/image
> 
> the full error is:
> 
> Namespace(input_path='home/anthony/Downloads/AUairdrone_data/images/validate', output_path='home/anthony/Downloads/AUairdrone_data/image', save=True)
> Traceback (most recent call last):
> File "main.py", line 65, in
> file_list = data.get_inputfile()
> File "main.py", line 30, in get_inputfile
> a = sorted(os.listdir(path))
> FileNotFoundError: [Errno 2] No such file or directory: './home/anthony/Downloads/AUairdrone_data/images/validate/'
> 
> I'm not sure if it's just syntax or something that is not compatible, anyone know how to resolve this?
